export default {
  bosses: [
    'kill kraid',
    'kill phantoon',
    'kill draygon',
    'kill ridley',
    'kill one G4',
    'kill two G4',
    'kill three G4',
    'kill all G4',
  ],
  minibosses: [
    'kill spore spawn',
    'kill botwoon',
    'kill crocomire',
    'kill golden torizo',
    'kill one miniboss',
    'kill two minibosses',
    'kill three minibosses',
    'kill all mini bosses',
  ],
  collect: [
    'collect 25% items',
    'collect 50% items',
    'collect 75% items',
    'collect 100% items',
    'collect all upgrades',
  ],
  clear: [
    'clear crateria',
    'clear green brinstar',
    'clear red brinstar',
    'clear wrecked ship',
    "clear kraid's lair",
    'clear upper norfair',
    "clear croc's lair",
    'clear lower norfair',
    'clear west maridia',
    'clear east maridia',
  ],
  meme: [
    'tickle the red fish',
    'kill the orange geemer',
    'kill shaktool',
    'activate chozo robots',
    'visit the animals',
    'kill king cacatac',
  ],
}
