name: Build and Release
run-name: Build and Release
on: [push]
permissions:
  contents: write
jobs:
  Build-and-release:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: client/yarn.lock
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: icons/yarn.lock
      - name: Build icons
        working-directory: './icons'
        run: yarn install && yarn build
      - name: Build client
        working-directory: './client'
        run: yarn install && yarn build:varia
      - name: Check Results
        run: ls && echo client && ls client && echo icons && ls icons