name: Build and Release
run-name: Build and Release
on: [push]
permissions:
  contents: write
jobs:
  versionNumber:
    outputs:
      output1: ${{ steps.semver.outputs.semver}}
    steps:
      - id: semver
        run: |
          PACKAGE_VERSION=$(cat client/package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[\",]//g')
  Build-and-release:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set tag name
        id: tag

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: client/yarn.lock

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: icons/yarn.lock

      - name: Build icons
        working-directory: './icons'
        run: yarn install && yarn build

      - name: Build client
        working-directory: './client'
        run: yarn install && yarn build:varia && tar -czvf release.tar.gz dist

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: true

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.tar.gz
          asset_name: release.tar.gz
          asset_content_type: application/gzip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}