name: Build and Release
run-name: Build and Release
on: [push]
jobs:
  Build-and-release:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: client/yarn.lock
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: icons/yarn.lock
      - name: Build client
        working-directory: './client'
        run: yarn install && yarn build:varia
      - name: Build client
        working-directory: './client'
        run: yarn build:github
      - run: ls
      - run: ls ../
      - run: ls ../../
      - name: Deploy github pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs